<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<!-- BenchmarkDotNet 要求 Release 模式运行，运行时自动切换 -->
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MainAPP\MainAPP.csproj" />
		<ProjectReference Include="..\Extensions\Extensions.csproj" />
	</ItemGroup>

</Project>
